### ISSUE TITLE
indentation limited to 2 spaces ?

### ISSUE THREAD

**Issue by vincent-peugnet** [kristoff-it/superhtml#46]
Hi and thanks for this superb tool! I'm very excited of using it during HTML workshops for beginners!

I did some tests, but I couldn't figure out how to use another indentation strategy (like using tabs, or 4 spaces)

I was wondering if it was a limitation of the project, or if I'm just missed something 🥴.

I'm on VS code:
```
Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 5.15.0-122-generic
```

with
```
Name: SuperHTML
Id: LorisCro.super
Description: Language Server for HTML and SuperHTML Templates.
Version: 0.5.1
Publisher: Loris Cro
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=LorisCro.super
```

**Comment by tanj** [comment]
I'm seeing the same thing in helix 24.7 with the language configured as:

```toml
[[language]]
name = "html"
scope = "source.html"
roots = []
file-types = ["html"]
language-servers = [ "superhtml-lsp" ]
indent = { tab-width = 4, unit = "    "}
```
